version: '3'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
    env_file: .env

  app:
    container_name: NS0.app
    build: .
    restart: always
    env_file: .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - redis